# Prometheus configuration for LocalAgent monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # LocalAgent application metrics
  - job_name: 'localagent'
    static_configs:
      - targets: ['localagent:8000']
    scrape_interval: 10s
    metrics_path: /metrics
    
  # Ollama server metrics
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    scrape_interval: 30s
    metrics_path: /api/ps  # Ollama process status
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    
  # Docker container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    
  # Node metrics (host system)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Application performance monitoring
  - job_name: 'localagent-providers'
    static_configs:
      - targets: ['localagent:8000']
    scrape_interval: 5s
    metrics_path: /metrics/providers
    scrape_timeout: 5s